name: release-please
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: rp
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json

      # if release is created - start our build/publish
      - name: Trigger build on release
        if: steps.rp.outputs.release_created == 'true'
        run: echo "Release created ${{ steps.rp.outputs.tag_name }}"
